name: 01-docker-build-and-push

on: 
    push:
        paths: 
            - "**01-docker-build-and-push**"

env:
    DOCKER_IMAGE_NAME: "mwas0122/github-actions-examples:01-docker-build-and-push"

jobs: 
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Build image
              run: docker build -t $DOCKER_IMAGE_NAME .

            - name: Run container
              run: docker run -d --rm -p 8080:80 $DOCKER_IMAGE_NAME

            - name: Test container
              run: curl --fail http://localhost:8080
