name: 02-multi-job-artifacts

on: 
    push:
        paths:
            - "**02-multi-job-artifacts**"
            - "!**README.md"

env: 
    PROJECT_DIR: "02-multi-job-artifacts"

jobs:
    build-jar:
        runs-on: ubuntu-latest
        steps: 
            - name: Fetch data
              uses: actions/checkout@v4
              with: 
                sparse-checkout: |
                  02-multi-job-artifacts
                  00-playground
                sparse-checkout-cone-mode: false

            - name: Display content
              run: |
                echo $(pwd)
                ls 
                echo "==="
                ls 02-multi-job-artifacts
            
            - name: Remove checkout result
              run: |
                rm -rf ./*
                ls

            - name: Checkout again with placeholder path
              uses: actions/checkout@v4
              with: 
                sparse-checkout: "02-multi-job-artifacts"
                sparse-checkout-cone-mode: true
            
            - name: Display content again
              run: |
                echo $(pwd)
                ls 
                echo "==="
                ls 02-multi-job-artifacts


