name: 02-multi-job-artifacts

on: 
    push:
        paths:
            - "**02-multi-job-artifacts**"
            - "!**README.md"

env: 
    PROJECT_DIR: 02-multi-job-artifacts
    ARTIFACT_NAME: build

jobs:
    build-jar:
        runs-on: ubuntu-latest
        steps: 
            - name: Fetch data
              uses: actions/checkout@v4
              with: 
                sparse-checkout: |
                  02-multi-job-artifacts
                sparse-checkout-cone-mode: false

            - name: Display content
              run: |
                cd $PROJECT_DIR
                chmod +x mnv/mvnw
                mvn/mvnw clean package

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with: 
                name: build
                path: $PROJECT_DIR/target/*.jar
                overwrite: true
                  
    run:
        runs-on: ubuntu-latest
        needs: build-jar
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with: 
                name: build

            - name: Run application
              run: java -jar *.jar
