name: 02-multi-job-artifacts

on: 
    push:
        paths:
            - "**02-multi-job-artifacts**"
            - "!**README.md"

env: 
    PROJECT_DIR: "02-multi-job-artifacts"

jobs:
    sparse-checkout-no-cone-mode:
        runs-on: ubuntu-latest
        steps: 
            - name: Fetch data
              uses: actions/checkout@v4
              with: 
                sparse-checkout: |
                  01-docker-build-and-push/Dockerfile
                  02-multi-job-artifacts
                sparse-checkout-cone-mode: false

            - name: Display content
              run: |
                ls 
                echo "====================="
                ls 01-docker-build-and-push
                echo "====================="
                ls 02-multi-job-artifacts
            
    sparse-checkout-cone-mode:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch data
              uses: actions/checkout@v4
              with: 
                sparse-checkout: |
                  01-docker-build-and-push/Dockerfile
                  02-multi-job-artifacts
            
            - name: Display content
              run: |
                ls 
                echo "====================="
                ls 01-docker-build-and-push
                echo "====================="
                ls 02-multi-job-artifacts


