name: 02-multi-job-artifacts

on: 
    push:
        paths:
            - "**02-multi-job-artifacts**"
            - "!**README.md"

env: 
    PROJECT_DIR: "02-multi-job-artifacts"

jobs:
    build-jar:
        runs-on: ubuntu-latest
        steps: 
            - name: Fetch data
              uses: actions/checkout@v4
              with: 
                filter: "02-multi-job-artifacts**"

            - name: Display content
              run: |
                echo $(pwd)
                ls 
                ls 02-multi-job-artifacts
            
            - name: Remove checkout result
              run: rm -rf 02-multi-job-artifacts

            - name: Checkout again with placeholder path
              uses: actions/checkout@v4
              with: 
                filter: "$PROJECT_DIR**"
            
            - name: Display content again
              run: |
                echo $(pwd)
                ls 
                ls $PROJECT_DIR
                ls 02-multi-job-artifacts


