name: 02-multi-job-artifacts

on: 
    push:
        paths:
            - "**02-multi-job-artifacts**"
            - "!**README.md"

jobs:
    build-jar:
        runs-on: ubuntu-latest
        steps: 
            - name: Display path to Java
              run: echo $JAVA_HOME

            - name: Display Java version
              run: java -version

            - name: Display all paths to Java
              run: ls /usr/lib/jvm/

            - name: Display all env vars
              run: printenv

    print-all-vars-linux:
        runs-on: linux-latest
        steps:
            - name: Print all vars
              run: printenv
