name: 03-deploy-via-ssh

on:
  push:
    paths:
      - "**03-deploy-via-ssh**"
      - "!**README.md"
  workflow_dispatch:
    inputs:
      command:
        description: Command to execute on the remote server
        default: | 
          whoami
          ls -al

jobs:
  test-connection:
    name: Test connection
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.MIKRUS_HOST }}
          username: ${{ secrets.MIKRUS_USER }}
          key: ${{ secrets.MIKRUS_KEY }}
          port: ${{ secrets.MIKRUS_PORT }}
          script: ${{ github.event.inputs.command }}
