name: 04-cache-dependencies

on:
  push:
    paths:
      - "**04-cache-dependencies**"
      - "!**README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout module files
      #   uses: actions/checkout@v4
      #   with:
      #     sparse-checkout: "04-cache-dependencies"
      #     sparse-checkout-cone-mode: false

      # - name: Config cache mandagement
      #   uses: actions/cache@v4
      #   with: 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build simple Dockerfile
        run: |
          cat >> Dockerfile<<EOF
          FROM nginx:stable-alpine3.21
          WORKDIR /test
          RUN echo "test" >> test.txt
          EOF

      - name: Run some docker image
        run: docker build --cache-to=type=local,dest=${{ runner.temp }}/.buildx-cache .

      - name: Verify docker cache
        run: |
          ls ${{ runner.temp }}
          echo "==========================="
          ls ${{ runner.temp }}/.buildx-cache

