name: 04-cache-dependencies

on:
  push:
    paths:
      - "**04-cache-dependencies**"
      - "!**README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout module files
      #   uses: actions/checkout@v4
      #   with:
      #     sparse-checkout: "04-cache-dependencies"
      #     sparse-checkout-cone-mode: false

      # - name: Config cache mandagement
      #   uses: actions/cache@v4
      #   with: 

      - name: Build simple docker compose file
        run: |
          cat >> docker-compose.yml<<EOF
          services:
            test: 
              image: nginx:stable-alpine3.21
              cache_to: type=local,dest=${{ runner.temp }}/.buildx-cache
          EOF

      - name: Run some docker image
        run: docker compose up -d

      - name: Verify docker cache
        run: |
          ls ${{ runner.temp }}
          echo "==========================="
          ls ${{ runner.temp }}/.buildx-cache

