name: Extract repository name from github context

on: 
  push:
    paths:
      - ".github/workflows/playground-02.yml"
  workflow_dispatch:

jobs:
  display_repository_name:
    runs-on: ubuntu-latest
    steps:
      - name: Extract
        env:
          OWNER_AND_REPO: ${{ github.repository }}
        run: |
          echo "REPO_NAME_CUT=$(echo "$OWNER_AND_REPO" | cut -d/ -f2)" >> $GITHUB_ENV
          echo "REPO_NAME_BASH=${OWNER_AND_REPO#*/}" >> $GITHUB_ENV

      - name: Display 
        run: |
          echo "Repo name extracted with cut: $REPO_NAME_CUT"
          echo "Repo name extracted with string manipulation script: $REPO_NAME_BASH"
  